version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: build
    ports:
      - 8000:8000
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=chatbot
      - MONGO_USER=root
      - MONGO_PASSWORD=secret
      - MONGO_AUTH_DB=admin
      - MONGO_SESSIONS_COLLECTION=sessions
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=""
      - REDIS_EXPIRE=3600
      - API_KEY=
      - OPENAI_API_KEY=
    networks:
      - chat
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8003:8001
    volumes:
      - redis_data:/data
    networks:
      - chat

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/:/docker-entrypoint-initdb.d/
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=secret
    - MONGO_INITDB_DATABASE=admin
    networks:
      - chat

networks:
  chat:
    driver: bridge

volumes:
  mongodb:
  mongodb_config:
  redis_data:





